# Site settings
title: "Learning English with Ms. Thuy"
description: "Fun and effective English lessons for everyone"
baseurl: "/learn-with-ms-thuy"   # ✅ QUAN TRỌNG: đúng tên repo
url: "https://ms-thuy-classes.github.io"

# Build settings
markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - .gitignore
  - Gemfile
  - Gemfile.lock
